name: Deploy the frontend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          build-args:
            - DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: krishna2302/todo-app-frontend:${{ github.sha }}
            